force-app/main/default/objects/Team_Projects__c/Team_Projects__c.object-meta.xml
<CustomObject>
    <label>Team Projects</label>
    <nameField>
        <label>Team Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Tasks__c/Team_Tasks__c.object-meta.xml
<CustomObject>
    <label>Team Tasks</label>
    <nameField>
        <label>Team Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Tasks__c/fields/Tasks_Hours_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Hours_Estimated__c</fullName>
    <label>Tasks Hours Estimated</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Tasks_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Priority__c</fullName>
    <label>Tasks Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Tasks_Status__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Status__c</fullName>
    <label>Tasks Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Team_Projects__c.field-meta.xml
<CustomField>
    <fullName>Team_Projects__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Projects</label>
    <referenceTo>Team_Projects__c</referenceTo>
    <relationshipLabel>Team Tasks</relationshipLabel>
    <relationshipName>Team_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TeamTasks_CRUD.cls
public with sharing class TeamTasks_CRUD {
    public TeamTasks_CRUD() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Team_Tasks__c> getAllTeamTasks() {
        List<Team_Tasks__c> teamTasks = [
            SELECT Id, Name, Team_Projects__r.Name, 
            Tasks_Priority__c, Tasks_Due_Date__c, 
            Tasks_Assigned_To__r.Name, Tasks_Status__c, 
            Tasks_Hours_Estimated__c 
            FROM Team_Tasks__c
        ];

        return teamTasks;
    }

    @AuraEnabled(cacheable=false)
    public static void handleCreateTask(
        String taskName,
        String taskProject,
        String taskPriority, 
        String taskAssignedTo, 
        Date taskDueDate, 
        Integer taskEstimatedTime
    ) {
        Team_Tasks__c newTask = new Team_Tasks__c(
            Name = taskName,
            Team_Projects__c = taskProject,
            Tasks_Priority__c = taskPriority,
            Tasks_Assigned_To__c = taskAssignedTo,
            Tasks_Due_Date__c = taskDueDate,
            Tasks_Hours_Estimated__c = taskEstimatedTime
        );
        
        insert newTask;
    }
}