force-app/main/default/objects/Team_Members__c/Team_Members__c.object-meta.xml
<CustomObject>
    <label>Team Members</label>
    <nameField>
        <label>Team Members Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Members__c/fields/Team_Members_Email__c.field-meta.xml
<CustomField>
    <fullName>Team_Members_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Team Members Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Team_Projects__c/Team_Projects__c.object-meta.xml
<CustomObject>
    <label>Team Projects</label>
    <nameField>
        <label>Team Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Tasks__c/Team_Tasks__c.object-meta.xml
<CustomObject>
    <label>Team Tasks</label>
    <nameField>
        <label>Team Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Tasks__c/fields/Tasks_Hours_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Hours_Estimated__c</fullName>
    <label>Tasks Hours Estimated</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Tasks_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Priority__c</fullName>
    <label>Tasks Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Team_Members__c.field-meta.xml
<CustomField>
    <fullName>Team_Members__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Members</label>
    <referenceTo>Team_Members__c</referenceTo>
    <relationshipLabel>Team Tasks</relationshipLabel>
    <relationshipName>Team_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Tasks__c/fields/Team_Projects__c.field-meta.xml
<CustomField>
    <fullName>Team_Projects__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Projects</label>
    <referenceTo>Team_Projects__c</referenceTo>
    <relationshipLabel>Team Tasks</relationshipLabel>
    <relationshipName>Team_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ARP_TestSetUp.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
global class ARP_TestSetUp {

    @TestSetup
    global static void ARP_SetupData() {
        Team_Projects__c project1 = new Team_Projects__c(Name = 'Project 1');
        insert project1;

        Team_Members__c member1 = new Team_Members__c(Name = 'Member 1', Team_Members_Email__c = 'member1@example.com');
        insert member1;

        Team_Tasks__c task1 = new Team_Tasks__c(
            Name = 'Task 1',
            Team_Projects__c = project1.Id,
            Tasks_Priority__c = 'High',
            Tasks_Assigned_To__c = member1.Id,
            Tasks_Due_Date__c = Date.today().addDays(7),
            Tasks_Hours_Estimated__c = 5
        );

        insert task1;
    }
}